# Generated by Django 3.1.7 on 2021-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='请输入接口名称', max_length=32, verbose_name='接口名称')),
                ('api_describe', models.TextField(default='请输入接口描述', max_length=255, verbose_name='接口描述')),
                ('api_manager', models.CharField(default='请输入接口负责人名字', max_length=11, verbose_name='接口负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
                'db_table': 'api_info',
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, verbose_name='发布日志id')),
                ('jid', models.CharField(max_length=16, verbose_name='日志id')),
                ('create_time', models.DateField(auto_now=True, verbose_name='日志创建时间')),
                ('type', models.CharField(max_length=16, verbose_name='日志类型')),
                ('context', models.CharField(max_length=30000, verbose_name='正文')),
                ('thumbsUp', models.IntegerField(default=0, verbose_name='点赞数')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('introduce', models.CharField(max_length=256, verbose_name='日志简介')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('mail', models.CharField(max_length=32, unique=True, verbose_name='邮箱')),
                ('createTime', models.DateField(verbose_name='注册时间')),
                ('isTeacher', models.BooleanField(default=False, verbose_name='是否为导师')),
            ],
        ),
    ]
