# Generated by Django 3.1.7 on 2021-05-13 00:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(default='No name', max_length=256, verbose_name='书名')),
                ('publishTime', models.DateField(default='2000-01-01', verbose_name='出版时间')),
                ('ISBN', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ISBN编号')),
                ('author', models.CharField(default='author', max_length=32, verbose_name='作者名字')),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='学习', max_length=16, verbose_name='圈子类型')),
                ('name', models.CharField(default='root', max_length=32, verbose_name='圈子名字')),
                ('ctime', models.DateField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('number', models.IntegerField(default=1, verbose_name='圈子人数')),
                ('creator', models.IntegerField(default=1, verbose_name='创建者id')),
            ],
        ),
        migrations.CreateModel(
            name='MailKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=32, unique=True, verbose_name='邮箱')),
                ('key', models.CharField(max_length=16, verbose_name='验证码')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='0', max_length=32, verbose_name='标签内容')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=16, verbose_name='密码')),
                ('sex', models.IntegerField(default=0, verbose_name='性别')),
                ('mail', models.EmailField(max_length=32, unique=True, verbose_name='邮箱')),
                ('avatar', models.CharField(default='NO', max_length=2048, verbose_name='头像')),
                ('createTime', models.DateField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('isTeacher', models.BooleanField(default=False, verbose_name='是否为导师')),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.circle', verbose_name='圈子')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True, verbose_name='token随机码')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='token对应的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=8195, verbose_name='笔记内容')),
                ('ntime', models.DateField(verbose_name='发布时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.book')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='笔记作者')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True, verbose_name='日志创建时间')),
                ('type', models.CharField(default='None', max_length=16, verbose_name='日志类型')),
                ('context', models.FileField(max_length=2048, upload_to='journal/%Y/%m/%d/', verbose_name='正文')),
                ('thumbsUp', models.IntegerField(default=0, verbose_name='点赞数')),
                ('title', models.CharField(default='0', max_length=64, verbose_name='标题')),
                ('introduce', models.CharField(default='0', max_length=256, verbose_name='日志简介')),
                ('pin', models.BooleanField(default=False, verbose_name='置顶')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='发布人')),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('context', models.CharField(max_length=256, verbose_name='内容')),
                ('floor', models.IntegerField(default=0, verbose_name='讨论楼层')),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.circle')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateField(auto_now=True, verbose_name='评论时间')),
                ('context', models.FileField(max_length=2048, upload_to='comment/%Y/%m/%d/', verbose_name='正文')),
                ('floor', models.IntegerField(default=0, verbose_name='评论楼层')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.journal', verbose_name='评论日志')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='评论人用户名')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.book')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=0, verbose_name='评论楼层')),
                ('bctime', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('context', models.TextField(default='0', verbose_name='书评内容')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.book')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='评论人用户名')),
            ],
        ),
    ]
