# Generated by Django 3.1.7 on 2021-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/media/1/file/dbf2c6b8.jpeg', max_length=1024, verbose_name='头像'),
        ),
    ]
