# Generated by Django 3.1.7 on 2021-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='context',
            field=models.CharField(max_length=3000, verbose_name='正文'),
        ),
    ]
