# Generated by Django 3.1.7 on 2021-06-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='article', max_length=32, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='type',
            field=models.CharField(default='discuss', max_length=32, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(default='No name', max_length=256, verbose_name='书名')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('ISBN', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ISBN编号')),
                ('author', models.CharField(max_length=32, verbose_name='作者名字')),
                ('press', models.CharField(max_length=32, verbose_name='出版社')),
                ('href', models.CharField(default='https://www.baidu.com/', max_length=1024, verbose_name='这个是一定要删掉的')),
                ('img', models.CharField(max_length=1024, verbose_name='封面')),
                ('downloadCount', models.IntegerField(default=0, verbose_name='下载数')),
                ('viewsCount', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='上传者')),
            ],
        ),
    ]
