# Generated by Django 3.1.7 on 2021-05-14 06:54

from django.db import migrations, models
import django1.models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='no', upload_to=django1.models.book_directory_path, verbose_name='书'),
        ),
    ]
