# Generated by Django 3.1.7 on 2021-06-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0002_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slogan',
            field=models.CharField(default='这个人很懒', max_length=256, verbose_name='签名'),
        ),
    ]
