# Generated by Django 3.1.7 on 2021-05-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0002_auto_20210507_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.book'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='评论人用户名'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.book'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.journal', verbose_name='评论日志'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='评论人用户名'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.circle'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django1.circle', verbose_name='圈子'),
        ),
    ]
