# Generated by Django 3.1.7 on 2021-05-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0003_auto_20210507_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True, verbose_name='token随机码')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.user', verbose_name='token对应的用户')),
            ],
        ),
    ]
