# Generated by Django 3.1.7 on 2021-06-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0003_auto_20210613_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='django1.user', verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='toUser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='django1.user', verbose_name='回复人'),
        ),
    ]
