# Generated by Django 3.1.7 on 2021-05-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0004_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=32, unique=True, verbose_name='邮箱')),
                ('key', models.CharField(max_length=16, verbose_name='验证码')),
            ],
        ),
    ]
