# Generated by Django 3.1.7 on 2021-06-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0004_auto_20210613_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.TextField(verbose_name='正文')),
                ('fromUserAvatar', models.CharField(max_length=512, verbose_name='评论者')),
                ('fromUserName', models.CharField(max_length=512, verbose_name='评论者名字')),
                ('toUserId', models.IntegerField(default=0, verbose_name='回复者id')),
                ('toUserName', models.CharField(default='', max_length=512, verbose_name='回复者名字')),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django1.discuss')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussFromUser', to='django1.user', verbose_name='评论人')),
                ('toUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussToUser', to='django1.user', verbose_name='回复人')),
            ],
        ),
    ]
