# Generated by Django 3.1.7 on 2021-05-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0005_mailkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='creator',
            field=models.IntegerField(default=1, verbose_name='创建者id'),
        ),
        migrations.AddField(
            model_name='circle',
            name='name',
            field=models.CharField(default='root', max_length=32, verbose_name='圈子名字'),
        ),
        migrations.AddField(
            model_name='circle',
            name='number',
            field=models.IntegerField(default=0, verbose_name='圈子人数'),
        ),
    ]
